---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /Users/{{ ansible_user_id }}/.oh-my-zsh
  - role: osxc.repository
    clone_url: git@bitbucket.org:ajenkins/vim.git
    dest: /Users/{{ ansible_user_id }}/Documents/git/vim
    links:
    - src: vimrc
      dest: /Users/{{ ansible_user_id }}/Documents/git/vim/.vimrc
  # - role: osxc.repository
  #   clone_url: https://github.com/gmarik/vundle.git
  #   dest: /Users/{{ ansible_user_id }}/.vim/bundle/vundle
  - role: osxc.repository
    clone_url: https://github.com/demon012/dotfiles.git
    dest: /Users/{{ ansible_user_id }}/Documents/git/dotfiles
    links:
    - src: /Users/{{ ansible_user_id }}/Documents/git/dotfiles
      dest: /Users/{{ ansible_user_id }}/.yadr/
  post_tasks:
    - command: ./install.sh chdir=/Users/{{ ansible_user_id }}/.yadr/

- hosts: all
  roles:
  - osxc.common-env
